__author__ = 'Dani'


class KeyDicts(object):

    #INDICATOR KEYS
    TOTAL_DEALS = 0
    AGRICULTURE_DEALS = 1
    CONSERVATION_DEALS = 2
    INDUSTRY_DEALS = 3
    RENEWABLE_ENERGY_DEALS = 4
    TOURISM_DEALS = 5
    OTHER_DEALS = 6
    UNKNOWN_DEALS = 7
    FORESTRY_DEALS = 99

    INTENDED_DEALS = 8
    CONCLUDED_DEALS = 9
    FAILED_DEALS = 10

    HECTARES_TOTAL_DEALS = 11
    HECTARES_INTENDED_DEALS = 12
    HECTARES_CONTRACT_DEALS = 13
    HECTARES_PRODUCTION_DEALS = 14